name: CI/CD with remote ssh
on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/checkout@v3
      - run: mkdir ./src/main/resources
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run: cat ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Docker build and push
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/vehicle-service .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/vehicle-service
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY}}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose -f docker-compose.vehicle.yml down --rmi all
            docker-compose -f docker-compose.vehicle.yml up -d
            docker ps
